version: '3.9'
services:
  portfolio:
    build: .
    container_name: mi-portfolio-nextjs
    restart: always
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - RESEND_API_KEY=${RESEND_API_KEY:-}
      - REMOVE_BG_API_KEY=${REMOVE_BG_API_KEY:-}
