"use client";

import React, { useState } from "react";
import { motion } from "framer-motion";
import { FileCheck, Copy, CheckCircle2, Download } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

interface TechCategory {
    name: string;
    techs: { name: string; template: string }[];
}

const techCategories: TechCategory[] = [
    {
        name: "Lenguajes",
        techs: [
            { name: "Node", template: "node_modules/\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n.npm\n.yarn\n.pnp.*" },
            { name: "Python", template: "__pycache__/\n*.py[cod]\n*.egg-info/\ndist/\nbuild/\n.Python\nvenv/\nENV/\n.venv" },
            { name: "Java", template: "*.class\n*.jar\n*.war\ntarget/\n.gradle/\nbuild/" },
            { name: "Go", template: "*.exe\n*.dll\n*.so\n*.dylib\n*.test\n*.out\nvendor/" },
            { name: "Rust", template: "target/\nCargo.lock\n**/*.rs.bk" },
        ],
    },
    {
        name: "Frameworks",
        techs: [
            { name: "React/Next.js", template: ".next/\nout/\nbuild/\n.vercel\n.turbo" },
            { name: "Vue/Nuxt", template: ".nuxt/\ndist/\n.output/" },
            { name: "Django", template: "*.log\n*.pot\n*.pyc\ndb.sqlite3\nmedia/\nstaticfiles/" },
            { name: "Laravel", template: "vendor/\nbootstrap/cache/\nstorage/\n.env" },
        ],
    },
    {
        name: "Herramientas",
        techs: [
            { name: "Git", template: ".git/\n*.orig" },
            { name: "VS Code", template: ".vscode/\n*.code-workspace" },
            { name: "JetBrains", template: ".idea/\n*.iml\n*.iws" },
            { name: "Docker", template: "*.dockerignore\ndocker-compose.override.yml" },
        ],
    },
    {
        name: "Sistemas Operativos",
        techs: [
            { name: "Windows", template: "Thumbs.db\nehthumbs.db\nDesktop.ini\n$RECYCLE.BIN/" },
            { name: "macOS", template: ".DS_Store\n.AppleDouble\n.LSOverride\n._*" },
            { name: "Linux", template: "*~\n.directory\n.Trash-*" },
        ],
    },
    {
        name: "Otros",
        techs: [
            { name: "Logs", template: "*.log\nlogs/\nnpm-debug.log*" },
            { name: "Env Files", template: ".env\n.env.local\n.env.*.local" },
            { name: "Cache", template: ".cache/\n.temp/\n.tmp/" },
            { name: "Backups", template: "*.bak\n*.backup\n*.swp\n*.swo" },
        ],
    },
];

export default function GitignoreGeneratorPage() {
    const [selectedTechs, setSelectedTechs] = useState<Set<string>>(new Set());
    const [customContent, setCustomContent] = useState("");
    const [copied, setCopied] = useState(false);

    const toggleTech = (techName: string) => {
        const newSelected = new Set(selectedTechs);
        if (newSelected.has(techName)) {
            newSelected.delete(techName);
        } else {
            newSelected.add(techName);
        }
        setSelectedTechs(newSelected);
    };

    const generateGitignore = (): string => {
        let content = "# Generated by Fernando Máximo's Dev Hub\n";
        content += `# Date: ${new Date().toLocaleDateString()}\n\n`;

        techCategories.forEach((category) => {
            const selectedInCategory = category.techs.filter((tech) => selectedTechs.has(tech.name));
            if (selectedInCategory.length > 0) {
                content += `# ========================================\n`;
                content += `# ${category.name}\n`;
                content += `# ========================================\n\n`;

                selectedInCategory.forEach((tech) => {
                    content += `# ${tech.name}\n`;
                    content += `${tech.template}\n\n`;
                });
            }
        });

        if (customContent.trim()) {
            content += `# ========================================\n`;
            content += `# Custom entries\n`;
            content += `# ========================================\n\n`;
            content += customContent.trim() + "\n";
        }

        return content;
    };

    const gitignoreContent = generateGitignore();

    const handleCopy = async () => {
        try {
            await navigator.clipboard.writeText(gitignoreContent);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        } catch (err) {
            console.error("Failed to copy text: ", err);
        }
    };

    const handleDownload = () => {
        const blob = new Blob([gitignoreContent], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = ".gitignore";
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div className="container mx-auto px-4 py-8 max-w-7xl">
            <motion.div
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="mb-8"
            >
                <div className="flex items-center gap-3 mb-2">
                    <div className="p-2 bg-slate-500/10 rounded-lg">
                        <FileCheck className="w-6 h-6 text-slate-500" />
                    </div>
                    <h1 className="text-3xl font-bold tracking-tight">.gitignore Generator</h1>
                </div>
                <p className="text-muted-foreground">
                    Genera archivos .gitignore personalizados según tu stack tecnológico con templates actualizados.
                </p>
            </motion.div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                {/* Selector de tecnologías */}
                <motion.div
                    className="lg:col-span-2 space-y-6"
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.1 }}
                >
                    {techCategories.map((category, catIndex) => (
                        <Card key={category.name} className="border-border/50 shadow-sm">
                            <CardHeader className="py-3 px-4 border-b bg-muted/20">
                                <CardTitle className="text-sm font-medium">{category.name}</CardTitle>
                            </CardHeader>
                            <CardContent className="p-4">
                                <div className="grid grid-cols-2 md:grid-cols-3 gap-2">
                                    {category.techs.map((tech, techIndex) => (
                                        <motion.button
                                            key={tech.name}
                                            initial={{ opacity: 0, scale: 0.9 }}
                                            animate={{ opacity: 1, scale: 1 }}
                                            transition={{ delay: 0.2 + catIndex * 0.05 + techIndex * 0.02 }}
                                            onClick={() => toggleTech(tech.name)}
                                            className={`py-2 px-4 rounded-lg text-sm font-medium transition-all ${
                                                selectedTechs.has(tech.name)
                                                    ? "bg-slate-500/20 text-slate-400 border border-slate-500/30 ring-1 ring-slate-500/20"
                                                    : "bg-muted/50 text-muted-foreground hover:bg-muted"
                                            }`}
                                        >
                                            {tech.name}
                                        </motion.button>
                                    ))}
                                </div>
                            </CardContent>
                        </Card>
                    ))}

                    {/* Custom entries */}
                    <Card className="border-border/50 shadow-sm">
                        <CardHeader className="py-3 px-4 border-b bg-muted/20">
                            <CardTitle className="text-sm font-medium">Entradas Personalizadas</CardTitle>
                        </CardHeader>
                        <CardContent className="p-0">
                            <textarea
                                className="w-full h-32 p-4 bg-transparent border-none resize-none focus:outline-none focus:ring-0 font-mono text-sm"
                                placeholder="# Añade tus propias rutas o patrones aquí&#10;mi-carpeta/&#10;*.custom"
                                value={customContent}
                                onChange={(e) => setCustomContent(e.target.value)}
                            />
                        </CardContent>
                    </Card>
                </motion.div>

                {/* Preview */}
                <motion.div
                    initial={{ opacity: 0, x: 20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: 0.2 }}
                    className="space-y-4"
                >
                    <Card className="border-border/50 shadow-sm bg-muted/10 sticky top-8">
                        <CardHeader className="py-3 px-4 flex flex-row items-center justify-between border-b bg-muted/40">
                            <CardTitle className="text-sm font-medium flex items-center gap-2">
                                <FileCheck className="w-4 h-4 text-slate-500" />
                                Vista Previa
                            </CardTitle>
                            <div className="flex gap-2">
                                <Button
                                    size="sm"
                                    variant="outline"
                                    className="h-8 gap-1.5"
                                    onClick={handleDownload}
                                    disabled={selectedTechs.size === 0 && !customContent.trim()}
                                >
                                    <Download className="w-4 h-4" /> .gitignore
                                </Button>
                                <Button
                                    size="sm"
                                    variant={copied ? "default" : "outline"}
                                    className={`h-8 gap-1.5 ${copied ? "bg-slate-600 hover:bg-slate-700 text-white" : ""}`}
                                    onClick={handleCopy}
                                    disabled={selectedTechs.size === 0 && !customContent.trim()}
                                >
                                    {copied ? (
                                        <>
                                            <CheckCircle2 className="w-4 h-4" /> ¡Copiado!
                                        </>
                                    ) : (
                                        <>
                                            <Copy className="w-4 h-4" /> Copiar
                                        </>
                                    )}
                                </Button>
                            </div>
                        </CardHeader>
                        <CardContent className="p-0 max-h-[calc(100vh-250px)] overflow-auto">
                            {selectedTechs.size > 0 || customContent.trim() ? (
                                <pre className="p-4 font-mono text-xs leading-relaxed text-muted-foreground whitespace-pre-wrap">
                                    {gitignoreContent}
                                </pre>
                            ) : (
                                <div className="p-8 text-center text-muted-foreground/50">
                                    <FileCheck className="w-16 h-16 mb-4 mx-auto opacity-20" />
                                    <p className="text-sm">Selecciona tecnologías para generar tu .gitignore</p>
                                </div>
                            )}
                        </CardContent>
                    </Card>

                    <div className="bg-blue-500/5 rounded-lg p-4 border border-blue-500/20">
                        <p className="text-xs text-muted-foreground">
                            <strong className="text-foreground">💡 Tip:</strong> Coloca el archivo .gitignore en la raíz de tu
                            repositorio. Git ignorará automáticamente los archivos y carpetas especificados.
                        </p>
                    </div>
                </motion.div>
            </div>
        </div>
    );
}
